#' getEMMARecord
#'
#' @param res Functional Enrichment Analysis results (enrichResult, gseaResult ...)
#' generated by `EMMA_run()`
#'
#' @return list of metadata recorded during FEA runtime
#' @export
#'
#' @examples
#' data("de_res_IFNg_vs_naive", package = "EMMA")
#' data("universe", package = "EMMA")
#' library("clusterProfiler")
#' res <- EMMA_run(enrichGO(gene = rownames(de_res_IFNg_vs_naive),
#' universe = universe, keyType = "ENSEMBL", OrgDb = org.Hs.eg.db::org.Hs.eg.db,
#' ont = "BP"))
#' getEMMARecord(res)
getEMMARecord <- function(res){
  
  rec <- attr(res, "EMMA_record")
  
  if (is.null(rec)) {
    stop("No `EMMA_record` was found. Try running `EMMA_run()` first.")
  }
  
  if (!is.list(rec)) {
    stop("Invalid structure. `EMMA_record` must be a `list`")
  }
  
  attr(res, "EMMA_record")
}